# An introduction to Numpy

Copyright (C) 2023, Forrest Sheng Bao

Numpy is a Python library that provides data structure and operation support for matrix-like data structures. It allows numerical computation in Python easier: partially allowing programmers to write more concise code. 

## n-D Arrays
An n-D array is basically a Python list. The type is `numpy.ndarray` defined in the `numpy` module. A `numpy.ndarray` object can be instantiated by simply passing a Python list to it. 

n-D means the dimension can be any integer `n`. 

In [1]:
import numpy

In [2]:
a_2d_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
a_2d_array = numpy.array(a_2d_list)
print(a_2d_array)
print(type(a_2d_array))
print(a_2d_array.shape)
print(a_2d_array.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)
int64


`shape` and `dtype` are very important attributes of a `numpy.ndarray`. `shape` tells the size of the array on each dimension. `dtype` tells the type of all elements. 


But unlike a Python list which can have inequal number and/or heterogenous types of element, it is not recommended to do so for `numpy.ndarray`: 

In [3]:
a_2d_list = [[1, 2, 3], [4, 5]]
a_2d_array = numpy.array(a_2d_list)

/tmp/ipykernel_543136/3888878709.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a_2d_array = numpy.array(a_2d_list)


In [4]:
print(a_2d_array.dtype)
print (a_2d_array)

object
[list([1, 2, 3]) list([4, 5])]


You get an array whose elements are Python `list`s. 

## Indexing and slicing of `numpy.ndarray`

In [5]:
a_2d_array = numpy.array(
    [
        [1, 2, 3, 4, 5], 
        [6, 7, 8, 9, 10], 
        [11, 12, 13, 14, 15]
    ]
)

print(a_2d_array[0]) # row 0
print(a_2d_array[1][2]) # row 1, column 2
print(a_2d_array[:, 2:4]) # all rows, columns 2 and 3, resulting in a sub-array
print(a_2d_array[1:3, 2:4]) # rows 1 and 2, columns 2 and 3, resulting in a sub-array

[1 2 3 4 5]
8
[[ 3  4]
 [ 8  9]
 [13 14]]
[[ 8  9]
 [13 14]]


`1:3` means a range from 1 to 2 (3-1). Slicing using `:` is called advanced slicing. Definitely read [this](https://numpy.org/doc/stable/user/basics.indexing.html#combining-advanced-and-basic-indexing)

In [25]:
# slicing using specific indices
a_1d_array = numpy.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print (a_1d_array[[0, 2, 5, 7]]) # elements 0, 2, 5, 7
print (a_2d_array[[0,2], [1,3]]) # row 0, column 1 and row 2, column 3

[1 3 6 8]
[ 2 14]


`numpy.newaxis` and its alias (not required to master in this class)

In [6]:
a_2d_array[:, None]

array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15]]])

## The Axis system

An axis corresponds to one level of indexing. In `a_2d_array[1][2]`, `1` is the value of axis 0, and `2` is the value of axis 1. When indexing, axis 0 is the first index, axis 1 is the second index, etc. Please definitely read [this](https://numpy.org/doc/stable/glossary.html#term-axis) 

### an operation along an axis

In [7]:
print ( numpy.max(a_2d_array, axis=0) ) # max of each column

# This is equivalent to: 
print ( [ max(a_2d_array[:, column_id]) for column_id in range(a_2d_array.shape[1])])


# what is shape[1]? the dimension along axis 1, which is the number of columns

print ( numpy.max(a_2d_array, axis=1) ) # max of each row

[11 12 13 14 15]
[11, 12, 13, 14, 15]
[ 5 10 15]


applying an operation **along an axis** means setting the axis to `:`, i.e., 
1. creating subarrays using all index (end-to-end slicing) in that axis, 
2. then applying the operation on each of the subarrays, and 
3. finally concatenating the results. 

In [8]:
# Remember this example earlier? 
a=numpy.array(
    [
        [
            [1,2], 
            [3,4]
        ], 
        [
            [5,6],
            [7,8]
        ]
    ]
)

print (numpy.max(a, axis=0)) # max of each 2x2 sub-array
print (numpy.max(a, axis=1)) # max of each 2-element row
print (numpy.max(a, axis=2)) # max of each 2-element column

[[5 6]
 [7 8]]
[[3 4]
 [7 8]]
[[2 4]
 [6 8]]


In [9]:
# The equivalants of the above are:
print (
    [
        [ max(a[:, axis_1_id, axis_2_id]) 
         for axis_2_id in range(a.shape[2]) ]
            for axis_1_id in range(a.shape[1])                  
    ]
)

print (
    [
        [ max(a[axis_0_id, :, axis_2_id]) 
            for axis_2_id in range(a.shape[2]) ] 
                for axis_0_id in range(a.shape[0]) 
    ]
)

print (
    [
        [ max(a[axis_0_id, axis_1_id, :]) 
            for axis_1_id in range(a.shape[1]) ] 
                for axis_0_id in range(a.shape[0]) 
    ]
)

[[5, 6], [7, 8]]
[[3, 4], [7, 8]]
[[2, 4], [6, 8]]


## map and reduce 
A related topic is map-reduce

In [10]:
def sqrt(a):
    return a**2 

print ( [  sqrt(x)    for x in range(5)   ] )

print (list( map(sqrt, [1,2,3, 4, 5]) ))

[0, 1, 4, 9, 16]
[1, 4, 9, 16, 25]


In [11]:
def plus(a,b): 
    return a+b

import functools 
print (functools.reduce (plus,  [1,2,3,4]))
print (functools.reduce (lambda x, y: (x,y) ,  [1,2,3,4]))

10
(((1, 2), 3), 4)


Applying an operation along an axis basically is mapping the operation on all subarrays obtained from slicing along that axis. 

Map allows easy parallelism: 

In [12]:
import time 
def foo(x):
    for _ in range(x):
        time.sleep(1) # sleep for 1 second
    return None 

x= 4

# time the execution of foo(x)
start_time = time.time()
foo(x)
print (time.time() - start_time)

import multiprocessing

# time the parallel version of foo(x)
start_time = time.time()
with multiprocessing.Pool() as p:
    p.map(foo, range(x))
print (time.time() - start_time)

4.003973722457886
3.0401740074157715


## Multiplications: vector-to-vector, vector-to-matrix, matrix-to-matrix

Actually there is no such a thing called a vector or a matrix in numpy. A vector is just a 1-D numpy array while a matrix is just a 2-D numpy array. 

In [13]:
a_vector = numpy.array([1,2,3,4,5])
another_vector = numpy.array([6,7,8,9,10])

# dot product between two vectors
print (numpy.dot(a_vector, another_vector))

# alternatively, we can use the @ operator
print (a_vector @ another_vector)

# another multplication is called hadamard product
# which is element-wise multiplication
print (a_vector * another_vector)

# in this class, we do not discuss cross product

130
130
[ 6 14 24 36 50]


In [14]:
a_matrix = numpy.array([[1,2,3], [4,5,6], [7,8,9]])
a_vector = numpy.array([1,2,3])

# matrix-vector multiplication
print (a_matrix @ a_vector)
# what is does is:
# 1*1 + 2*2 + 3*3 = 14
# 4*1 + 5*2 + 6*3 = 32
# 7*1 + 8*2 + 9*3 = 50

# alternatively, we can use matmul
print (numpy.matmul(a_matrix, a_vector))

# what about dot?
print (numpy.dot(a_matrix, a_vector))

# vector-matrix multiplication
print (a_vector @ a_matrix)
# what is does is:
# 1*1 + 2*4 + 3*7 = 30
# 1*2 + 2*5 + 3*8 = 36
# 1*3 + 2*6 + 3*9 = 42

# let's try matmul and dot too
print (numpy.matmul(a_vector, a_matrix))
print (numpy.dot(a_vector, a_matrix))

[14 32 50]
[14 32 50]
[14 32 50]
[30 36 42]
[30 36 42]
[30 36 42]


In the second case, `a_matrix` is treated as a matrix -- it is sliced column-wisely. 
What about the first case? **Broadcasting** happened. To be discussed later. 

`@` is a place holder for `matmul`, which stands for matrix multiplication. 

`matmul` and `dot` are the same for 2D numpy arrays (even 1D), although they differ for dimensions higher than 2. If you are interested, read [this](https://stackoverflow.com/questions/34142485/difference-between-numpy-dot-and-python-3-5-matrix-multiplication)

In [15]:
# Let's make sure its really doing what it should be doing
b_matrix = numpy.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
b_vector = numpy.array([1,2,3])

print (b_matrix @ b_vector) 
# thanks to broadcasting, this is the same as: (Copilot wrote this!!!)
print (b_matrix @ b_vector.reshape(3,1))
print (b_vector.reshape(3, 1))

# an error is expected here because of shape mismatch
print (b_vector @ b_matrix)

[14 32 50 68]
[[14]
 [32]
 [50]
 [68]]
[[1]
 [2]
 [3]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [23]:
# finally, matrix-to-matrix multiplication

a_matrix = numpy.array([[1,2,3], [4,5,6], [7,8,9]])
b_matrix = numpy.eye(3) + numpy.array([[1,1,0], [1,1,1], [0,1,1]])
print (b_matrix)
print (a_matrix @ b_matrix)
# what is does is:
# does GPT really understand math or code? 

print (b_matrix @ a_matrix)

[[2. 1. 0.]
 [1. 2. 1.]
 [0. 1. 2.]]
[[ 4.  8.  8.]
 [13. 20. 17.]
 [22. 32. 26.]]
[[ 6.  9. 12.]
 [16. 20. 24.]
 [18. 21. 24.]]


Reading: https://stackoverflow.com/questions/21562986/numpy-matrix-vector-multiplication

## Broadcasting 

In [ ]:
a_vector = numpy.array([1,2,3])
print (a_vector - 1 ) 

[0 1 2]


Wow! We have seen broadcasting above not long ago. To know more, not required, please read [this](https://numpy.org/doc/stable/user/basics.broadcasting.html). 

Broadcasting can be really useful, e.g., in HW2. 

In [ ]:
y = numpy.array([-1, 1, 1, -1, 1, 1])
X = numpy.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ]
)

# let's find out X rows where y value is 1 
print (X[y==1]) # the operator == is broadcasted to each element of y

[[ 4  5  6]
 [ 7  8  9]
 [13 14 15]
 [16 17 18]]


## Basic linear algebra operations in Numpy

In [ ]:
# transpose a vector
a_vector = numpy.array([1,2,3])
print (a_vector)
print (a_vector.T)

[1 2 3]
[1 2 3]


Why no difference? Because 1-D array cannot be transposed. Transposing an n-D array means swapping the two axis. 

In [ ]:
# transpose a matrix
a_matrix = numpy.array([[1,2,3], [4,5,6], [7,8,9]])
print (a_matrix)
print (a_matrix.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## Inverse of a matrix 

In [ ]:
a_matrix = numpy.array([[1,2,3], [4,5,6], [7,8,9]])
print (a_matrix)
print (numpy.linalg.det(a_matrix))
print (numpy.linalg.inv(a_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0.0


LinAlgError: Singular matrix

Why the error? Singularity! 

In [ ]:
a_matrix = numpy.array([[1,2,3], [4,3,6], [8,8,9]])

# Getting the inverse of a_matrix 
print (numpy.linalg.inv(a_matrix))

# check it's really the inverse 
print (a_matrix @ numpy.linalg.inv(a_matrix))


[[-0.77777778  0.22222222  0.11111111]
 [ 0.44444444 -0.55555556  0.22222222]
 [ 0.2962963   0.2962963  -0.18518519]]
[[1.00000000e+00 0.00000000e+00 5.55111512e-17]
 [2.22044605e-16 1.00000000e+00 1.11022302e-16]
 [4.44089210e-16 0.00000000e+00 1.00000000e+00]]


Why is it not absolutely an identity matrix?  Computational error. 

So how to check whether two matrixes are numerically equal? 

In [ ]:
print (
    numpy.isclose(
        a_matrix @ numpy.linalg.inv(a_matrix),
        numpy.eye(3)
    )
)

print (
    numpy.allclose( 
        a_matrix @ numpy.linalg.inv(a_matrix),
        numpy.eye(3)
    )
)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
True


## Ravel, squeeze, and reshape: changing the shape of arrays

In [ ]:
# an example of numpy ravel 
a_matrix = numpy.array([[1,2,3], [4,5,6], [7,8,9]])
print (a_matrix)
print (a_matrix.ravel())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# an example of numpy reshape
a_vector = numpy.array([1,2,3,4,5,6,7,8,9])
print (a_vector.reshape(3,3))
print (a_vector.reshape(1,-1)) # -1 means "whatever is needed", 
 # thus reshape(1, -1) means reshaping to one row and whatever number of columns
print (a_vector.reshape(-1,1)) # means reshaping to one column and whatever number of rows

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


You can reshape an array of any dimensions 

In [ ]:
# reshape a 2D array
a_matrix = numpy.array(range(8))
print (a_matrix.reshape(2,4))
print (a_matrix.reshape(2,4).reshape(4,2))

[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


You can even use reshape to increase dimensions. Actually `reshape(1,-1)` and `reshape(-1,1)` are special cases of dimension increase. 

In [ ]:
# reshape a 2D array
a_matrix = numpy.array(range(16))
print (a_matrix.reshape(2,8))
print (a_matrix.reshape(2,8).reshape(2,4,2))

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]


In [17]:
# Squeeze will "remove" all dimensions that is of shape 1 
a_matrix = numpy.array(range(16))
print (a_matrix.reshape(2,1, 8,1))
print (a_matrix.reshape(2,1, 8,1).squeeze())


[[[[ 0]
   [ 1]
   [ 2]
   [ 3]
   [ 4]
   [ 5]
   [ 6]
   [ 7]]]


 [[[ 8]
   [ 9]
   [10]
   [11]
   [12]
   [13]
   [14]
   [15]]]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


## Stack 

In [ ]:
# a 2D numpy array
a_matrix = numpy.array([[1,2,3], [4,5,6], [7,8,9]])
b_matrix = a_matrix * 2 

# vertically stack two matrices
print (numpy.vstack((a_matrix, b_matrix)))

# horizontally stack two matrices
print (numpy.hstack((a_matrix, b_matrix)))

# which are equivalent to numpy.concatenate
print (numpy.concatenate((a_matrix, b_matrix), axis=0))

# numpy.stack is slightly different, 
# which will increase on dimension along the axis in which the stacking happens
print (numpy.stack((a_matrix, b_matrix), axis=0)) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]]


## The Einstein notation

See https://app.codepod.io/repo/gx4t5ckk5r0t56httfxp